/**
 * Labels for the two client islands, kept in a server-safe module so
 * server components can import them without dragging a 'use client'
 * module's non-component exports through the RSC boundary.
 */

import type { IntakeLabels } from '@/components/IntakeForm';
import type { PlannerLabels } from '@/components/StackPlanner';

export const PLANNER_LABELS: Record<'en' | 'de', PlannerLabels> = {
  en: {
    csvLabel: 'SKU list (CSV: sku_id, length_mm, width_mm, height_mm, weight_kg, qty, max_stack_kg)',
    fileLabel: 'or drop a CSV file',
    pallet: 'Pallet',
    palletEur1: 'EPAL 1 — 1200 × 800',
    palletEur2: 'EPAL 2 — 1200 × 1000',
    palletCustom: 'Custom',
    length: 'Length mm',
    width: 'Width mm',
    maxHeight: 'Max stack mm',
    maxWeight: 'Max payload kg',
    stack: 'Stack',
    reset: 'Sample',
    layerMap: 'Layer map',
    layer: 'Layer',
    allLayers: 'All',
    stability: 'Stability',
    density: 'Density',
    layers: 'Layers',
    cycle: 'Cycle time',
    cycleNote: 'Cycle time at {s} s per pick, planning assumption.',
    height: 'Height',
    weight: 'Weight',
    placed: 'Placed',
    exportUr: 'Export URScript stub',
    exportCsv: 'Export plan CSV',
    scriptTitle: 'URScript stub (preview)',
    boundary: 'Static geometry: base support and centre of mass. Not a transport or wrapping certification.',
    state: 'Cell state',
  },
  de: {
    csvLabel: 'SKU-Liste (CSV: sku_id, length_mm, width_mm, height_mm, weight_kg, qty, max_stack_kg)',
    fileLabel: 'oder CSV-Datei wählen',
    pallet: 'Palette',
    palletEur1: 'EPAL 1 — 1200 × 800',
    palletEur2: 'EPAL 2 — 1200 × 1000',
    palletCustom: 'Eigenes Maß',
    length: 'Länge mm',
    width: 'Breite mm',
    maxHeight: 'Max. Stapel mm',
    maxWeight: 'Max. Nutzlast kg',
    stack: 'Stapeln',
    reset: 'Beispiel',
    layerMap: 'Lagenplan',
    layer: 'Lage',
    allLayers: 'Alle',
    stability: 'Stabilität',
    density: 'Dichte',
    layers: 'Lagen',
    cycle: 'Taktzeit',
    cycleNote: 'Taktzeit bei {s} s pro Griff, Planungsannahme.',
    height: 'Höhe',
    weight: 'Gewicht',
    placed: 'Gesetzt',
    exportUr: 'URScript-Stub exportieren',
    exportCsv: 'Plan als CSV exportieren',
    scriptTitle: 'URScript-Stub (Vorschau)',
    boundary: 'Statische Geometrie: Auflage und Schwerpunkt. Keine Transport- oder Wickelzertifizierung.',
    state: 'Zellenzustand',
  },
};

export const INTAKE_LABELS: Record<'en' | 'de', IntakeLabels> = {
  en: {
    company: 'Company',
    city: 'City',
    robot: 'Robot brand',
    robotOther: 'Other / none yet',
    sku: 'SKU file (CSV)',
    skuHint: 'Columns: sku_id, length_mm, width_mm, height_mm, weight_kg, qty. Same format as the planner above.',
    layout: 'Cell layout (PDF, optional)',
    email: 'Email',
    submit: 'Send the list',
    sending: 'Sending…',
    ok: 'Received. We answer with a stack and the unstable SKUs.',
    errGeneric: 'Sending failed on our side. Please email the file to',
    errUnconfigured: 'The intake is not wired up yet. Please email the file to',
    errEmail: 'That does not look like a valid email address. Or email the file to',
    errSku: 'Attach a SKU CSV. Or email the file to',
    errSize: 'File too large (CSV up to 2 MB, PDF up to 8 MB). Or email the file to',
    privacy: 'Your SKU data is used to answer this request and nothing else. Details in the privacy policy.',
  },
  de: {
    company: 'Firma',
    city: 'Stadt',
    robot: 'Robotermarke',
    robotOther: 'Andere / noch keiner',
    sku: 'SKU-Datei (CSV)',
    skuHint: 'Spalten: sku_id, length_mm, width_mm, height_mm, weight_kg, qty. Gleiches Format wie im Planer oben.',
    layout: 'Zellenlayout (PDF, optional)',
    email: 'E-Mail',
    submit: 'Liste senden',
    sending: 'Wird gesendet…',
    ok: 'Erhalten. Sie bekommen einen Stapel und die instabilen SKUs.',
    errGeneric: 'Das Senden ist auf unserer Seite fehlgeschlagen. Bitte senden Sie die Datei per E-Mail an',
    errUnconfigured: 'Die Annahme ist noch nicht angebunden. Bitte senden Sie die Datei per E-Mail an',
    errEmail: 'Das sieht nicht nach einer gültigen E-Mail-Adresse aus. Oder senden Sie die Datei an',
    errSku: 'Bitte hängen Sie eine SKU-CSV an. Oder senden Sie die Datei an',
    errSize: 'Datei zu groß (CSV bis 2 MB, PDF bis 8 MB). Oder senden Sie die Datei an',
    privacy: 'Ihre SKU-Daten werden nur zur Beantwortung dieser Anfrage verwendet. Details in der Datenschutzerklärung.',
  },
};
